services:

  baby-sleep-coach:
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - "0.0.0.0:${PORT}:80"
      - "0.0.0.0:${BACKEND_PORT}:8000"
      - "0.0.0.0:${RESOURCE_PORT}:8001"
    env_file:
      - stack.env
    volumes:
      - .:/usr/app/babysleepcoach
      - /usr/app/babysleepcoach/webapp/node_modules
    # To use a webcam, uncomment these lines
    # devices:
    #   - /dev/video0
